@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define SPRITESURL https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/v1.1/sprites
!includeurl SPRITESURL/python.puml
!includeurl SPRITESURL/docker.puml
!includeurl SPRITESURL/redis.puml
!includeurl SPRITESURL/sqlite.puml
!includeurl SPRITESURL/elasticsearch.puml
!includeurl SPRITESURL/kibana.puml
!includeurl SPRITESURL/linux-tux.puml
!includeurl SPRITESURL/nginx.puml
!includeurl SPRITESURL/react.puml


title Container Diagram - Codespace
skinparam titleFontSize 24
skinparam defaultFontSize 20
skinparam dpi 150

Person(student, "User", "Submits code and checks feedback")
Person(admin, "Admin", "Configures tasks and manages users")

System_Ext(email, "Mail Server")
System_Ext(moodle, "Moodle Platform", "User Groups", $link="https://moodle.uni-siegen.de/course/view.php?id=5258")



System_Boundary(s1, "Codespace System") {
  Container(codefrontend, "Codespace UI", "React / Vite", "Collaborative workspace.", $tags="UI", $sprite="react")
  Container(simfrontend, "Simulation UI", "React / Vite", "Simulation interface for visualization and interaction", $tags="UI", $sprite="react")
  Container(adminfrontend, "Admin UI", "React / Vite", "Frontend interface for Admins", $tags="UI", $sprite="react")
  Container(proxy, "Reverse Proxy", "Nginx", "Route Traffic to correct service", $sprite="nginx")
  Container(web, "FastAPI Web App", "Python / FastAPI", "Exposes REST API to users and admins", $sprite="python") 
  Container(worker, "Celery Worker", "Python / Celery", "Processes long-running background tasks", $sprite="python") 
  Container(docker, "Execution Engine", "Docker CLI", "Executes user code in isolated containers", $sprite="docker")
  ContainerDb(redis, "Redis", "Redis", "Caches test results and handles async task queue", $sprite="redis")
  ContainerDb(db, "SQLite Database", "SQLite", "Stores persistent data like users, results, and configs", $sprite="sqlite")
  Container(fs, "Filesystem", "Linux FS", "Stores uploaded files, logs, and test configs", $sprite="linux-tux")
  Container(logging, "Logging Stack", "ELK (Elasticsearch, Logstash, Kibana)", "System Logs, User Activity", $sprite="elasticsearch", $link="https://eslab.es.eti.uni-siegen.de/kibana/")
  Container(kibana, "Kibana", "Log Dashboard", $sprite="kibana", $link="https://eslab.es.eti.uni-siegen.de/kibana/")
}


Rel(student, codefrontend, "Access shared code editor, test runner, report submission, and group chat")
Rel(student, simfrontend, "Visualize and interact with runtime simulation")
Rel(codefrontend, proxy, "Sync code changes, tests, group messages, stdout streams", "HTTPS / WebSocket")
Rel(simfrontend, proxy, "Update/Get simulation state", "HTTPS")

' ==== ADMIN Relations ======
Rel(admin, adminfrontend, "Configures tasks and manages courses")
Rel(adminfrontend, proxy, "Sends task and course configuration requests", "HTTPS")
Rel(admin, proxy, "Monitor Dashboard", "HTTPS")
Rel(proxy, web, "Proxies Codespace and Simulation API traffic ", "HTTP")
Rel(proxy, kibana, " Proxies admin dashboard traffic ", "HTTP")

' ===== FastApi Layer =========

Rel(web, db, "Reads/Writes user submissions and authorization", "SQL")
Rel(web, redis, "async tasks and pub/sub for live updates", "Redis")
Rel(web, worker, "Dispatches background code execution", "Redis Queue")
Rel(web, fs, "Save user's code and logs", "File I/O")
Rel(web, docker, "Proxy to User's code / simulation server", "HTTP")
Rel(web, email, "Notifications/OTP", "SMTP")
Rel(fs, logging, "Ingest logs", "Filebeat")

Rel(worker, docker, "Spawns containers to execute code", "Docker CLI")
Rel(worker, redis, "Fetches job metadata and status / Store worker state", "Redis")
Rel(fs, moodle, "Stores group data exported from Moodle", "CSV")
Rel(kibana, logging, "log search and Dashboards")

SHOW_LEGEND()
@enduml

