@startuml
title Group Collaboration on Code and Interactive Simulation

actor GroupUser1
actor GroupUser2

participant "Frontend UI\n(Editor + Sim)" as UI
participant "Application Server" as Backend
participant "Docker Container" as Container
participant "PubSub / \n WebSocket Manager" as WS
participant "Task Queue" as Redis
participant "Worker" as Worker


GroupUser1 -> UI : Edit Code
UI -> Backend : WebSocket /editfile (group_id, file_id)
Backend -> WS : Publish code update (group_id)
WS -> Backend : Broadcast to all subscribers
Backend -> UI : WebSocket push (file update)
UI -> GroupUser2 : Display updated code

' ======= Execute/Test Code=====
GroupUser1 -> UI : Execute/Test Code
UI -> Backend : POST /submit (group_id, task_id)
Backend -> Redis : Enqueue code execution task
Worker -> Redis : Fetch task from queue
Worker -> Container : Launch container (group-task scoped)
activate Container

Container -> Container : Mount code and config
Container -> Container : Build + Run User code
Container -> WS : Send stdout
WS -> UI : Stream results to all group members
deactivate Container

UI -> GroupUser2 : Display results/output

GroupUser1 -> UI : Opens simulator at /sim/courseX/groupY/taskZ
GroupUser2 -> UI : Opens same simulator URL
UI -> Backend : GET /sim/taskX/groupY/taskZ
Backend -> Container : Route to internal simulator port
Container -> UI : Serve Web UI (e.g., pendulum simulator)

@enduml

