@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title System Context - Codespace
skinparam titleFontSize 24
skinparam defaultFontSize 20
skinparam dpi 150

' Place this at the top, before elements
LAYOUT_LEFT_RIGHT()

' === ACTORS ===
Person(user, "Student", "Submits and runs code")
Person(teacher, "Instructor", "Creates tests and reviews submissions")

' === SYSTEM UNDER DESIGN ===
System_Boundary(s1, "Codespace System") {
    System(codespace, "Codespace Platform", "Online platform for collaborative work and code execution in secure containers")
    
}

' === EXTERNAL SYSTEMS ===
System_Ext(email, "SMTP Service", "Sends email notifications")
System_Ext(moodle, "Moodle Platform", "Student Groups", $link="https://moodle.uni-siegen.de/course/view.php?id=5258")

' === RELATIONSHIPS ===
Rel(user, codespace, "Collaboratively edit, run and test code, submit report")
Rel(teacher, codespace, "Creates test cases, views reports")
Rel(codespace, email, "OTP authentication")
Rel(codespace, email, "Sends results and alerts")

Rel(user, moodle, "Form groups")
Rel(codespace, moodle, "Get Student Groups and Registrations")

LAYOUT_WITH_LEGEND()
@enduml

